// Renders docs/resolution-wire.md — the phone-readable proof that the v3 engine,
// wired into the live quest resolver, plays like the v1 one it sits beside. PURE
// and deterministic (same rules as resolve/sim.ts: no Date, Math.random or locale);
// wire.test.ts fails if the committed doc drifts from this code.

import { RESULT_LADDER } from "../content/ladder";
import { SKILL_IDS } from "../content/skills";
import { resolveQuest } from "../resolver";
import { HERO_DATA, PARTY_BY_ID, PARTY_DATA, partyTraitMod } from "../roster";
import type { BeatType } from "../types";
import { MOD_CAP, targetFor } from "../resolve/check";
import { GATE, SEEDS, calibrationRows, eligibleParties, modalShare, questBeats, QUESTS } from "./harness";
import { RESULT_TO_GRADE, SIZE_BONUS_PER_EXTRA, TRAIT_PCT_PER_DELTA } from "./bridge";

const pct = (p: number) => `${Math.round(p * 100)}%`;
const arrow = (a: number, b: number) => `${pct(a)} → ${pct(b)}`;
const row = (cells: (string | number)[]) => `| ${cells.join(" | ")} |`;
const table = (header: string[], rows: (string | number)[][]) => [row(header), row(header.map(() => "---")), ...rows.map(row)].join("\n");
const SHORT_PARTY: Record<string, string> = { "iron-vigil": "Vigil", "free-blades": "Blades", "lone-mira": "Mira" };
const short = (id: string) => SHORT_PARTY[id] ?? id;
const titleCase = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

/** The largest trait percentage any party can sum on any beat type (the engine caps it at ±MOD_CAP). */
function maxTraitPct(): number {
  const types: BeatType[] = ["investigation", "travel", "social", "combat"];
  let max = 0;
  for (const p of PARTY_DATA) for (const t of types) max = Math.max(max, Math.abs(partyTraitMod(p.id, t).delta) * TRAIT_PCT_PER_DELTA);
  return max;
}

/** A worked example from a real seeded run: the first Free Blades ambush that ends in Success. */
function workedExample(): string {
  const quest = QUESTS.find((q) => q.id === "road")!;
  for (let seed = 1; seed <= SEEDS; seed++) {
    const log = resolveQuest({ quest, partyId: "free-blades", cutPct: 10, durationDays: 1, seed, engine: "v3" });
    const beat = log.beats.find((b) => b.id === "road-ambush");
    if (beat?.check && beat.check.result === "success") {
      const c = beat.check;
      return `Road job, The Free Blades, ambush (seed ${seed}): capability ${c.capability}, dice ${c.dice[0]}+${c.dice[1]}, score ${c.score} against target ${c.target} (${Math.round((c.score / c.target) * 100)}%) → Success, meter ${beat.score}.`;
    }
  }
  return "(no Success example found)";
}

export function renderWire(): string {
  const out: string[] = [];
  const push = (...lines: string[]) => out.push(...lines);

  push(
    "# Resolution wire: v1 vs v3",
    "",
    "GENERATED by `npm run sim:wire` (web/src/game/guild/wire/report.ts). Do not edit by hand;",
    "`wire.test.ts` fails if this file drifts from the code. Real `resolveQuest` runs over fixed seeds",
    `1 to ${SEEDS}, both engines side by side.`,
    "",
    "**What changed for a player:** on the dev build (`/Game/dev/`) quests are graded by the v3 2d6 check.",
    "The report shows the result name (Critical Failure, Failure, Insufficient, Success, Triumph), a small",
    "\"Needed X, got Y\" line after each beat lands, and a \"Rules v3\" chip. Production (`/Game/`) still runs",
    "v1. Add `?engine=v1` or `?engine=v3` to any URL to force one. Old saved reports keep their v1 words.",
    "",
    "## How it plays",
    "",
    `- **Check:** capability = best member's (Attribute + Skill), plus trait percent (+${Math.round(TRAIT_PCT_PER_DELTA * 100)}% per old trait point,`,
    `  capped at ${Math.round(MOD_CAP * 100)}%, largest live sum ${Math.round(maxTraitPct() * 100)}%), plus ${SIZE_BONUS_PER_EXTRA} per extra party member, plus momentum.`,
    "  Score = capability + 2d6. Target = 6 + 0.30 × the beat's difficulty. A forced recovery raises the target by 30%.",
    "- **Combat** uses the temporary rule: best of Strength, Dexterity, Mind plus the hero's Combat value.",
    `- **Result to old grade slot** (so momentum, recovery and bonus logic are unchanged): ` +
      RESULT_LADDER.map((r) => `${r.name} → ${RESULT_TO_GRADE[r.id]}`).join(", ") + ".",
    "- **Stand-ins:** the flat size bonus and \"best member leads\" stand in for the open Cooperation Modes.",
    "- **Insufficient** (did not meet the requirement, costs nothing more) has its own line on every beat and earns no bonus-purse sweetener; v1's old \"ok\" line would have read as a win.",
    "",
    "## A. Same feel? (the gate)",
    "",
    `This slice's bar: success and bonus within ${Math.round(GATE.success * 100)} points of v1, strong beats per run within ${GATE.strong}.`,
    "It is a regression guard for this slice, not a design target; v3 is expected to diverge once growth and feats land.",
    "",
  );

  push(
    table(
      ["Quest · party", "Success v1 → v3", "Bonus v1 → v3", "Strong beats v1 → v3"],
      calibrationRows().map((r) => [
        `${r.quest.title} · ${short(r.partyId)}`,
        arrow(r.v1.success, r.v3.success),
        arrow(r.v1.bonus, r.v3.bonus),
        `${r.v1.strong.toFixed(2)} → ${r.v3.strong.toFixed(2)}`,
      ]),
    ),
    "",
    "\"v1 → v3\" reads before → after. **Strong beats** = Success or Triumph (old Great or Triumph) per run.",
    "Structural gates are unchanged: a lone recruit still cannot take the Road or the Ruins.",
    "",
    "**Honest reading:** v3 matches v1 on the contested quests (Road, Ruins). On the standing jobs and the Hidden",
    "reliquary bonus both engines are already safe, so the gate passes trivially and v3 is deterministic there.",
    "",
    "### Design flags (for Stefan to rule on)",
    "",
    "- **Risk-free jobs.** Standing jobs (100% success) and the Hidden reliquary (100% modal share for both",
    "  parties) carry no risk and no drama. Intended as a survival floor, or a later retune of those `diff3`s?",
    "- **Hero stats were fitted to v1 outcomes, not written by character.** Pell the Cutpurse has Reasoning 7",
    "  above Mobility 6, and Brok the Sellsword has Combat 7 below Force 9. Keep, or rewrite by character",
    "  and re-fit the difficulties?",
    "- **Zone icons keep their v1 positions.** The meter's hearts and laurels sit where they always did, so",
    "  \"Insufficient\" lands on the one-laurel zone that v1 called \"Success\". Relabelling the marks is a later UI slice.",
    "- **Mixed history.** Reports saved before the switch keep their v1 words; a report graded by v3 carries a",
    "  \"v3 rules\" tag in the story view, and the Report header shows \"Rules v3\" while v3 grades new quests.",
    "",
    "## B. Hero or luck? (v3 only)",
    "",
    "Per beat, the share of the single most likely result, no momentum (72% means the same result comes up",
    "72 times in 100). **T22 = target 22**, the score the party must reach. \"–\" = that party cannot take the quest.",
    "High = the hero decides the check, low = the dice do. **100% means no drama, not no risk:** nothing is",
    "left to chance, so the outcome is settled before the dice are thrown.",
    "",
  );

  const beatRows: (string | number)[][] = [];
  for (const q of QUESTS) {
    const eligible = eligibleParties(q);
    for (const b of questBeats(q)) {
      beatRows.push([
        `${b.location}`,
        `${titleCase(b.skill)} · T${targetFor(b.diff3)}`,
        ...PARTY_DATA.map((p) => (eligible.includes(p.id) ? pct(modalShare(p.id, b)) : "–")),
      ]);
    }
  }
  push(table(["Beat", "Skill · target", ...PARTY_DATA.map((p) => short(p.id))], beatRows), "");

  push("## C. The heroes (v3 stats)", "", "Veterans are pre-grown from use; Mira is a fresh recruit and follows the birth rule exactly (14 points, each 2 to 4, kit 2/1/1/1).", "");
  push(
    table(
      ["Hero", "Str/Dex/Con/Mind/Cha", "Best skills", "Combat"],
      HERO_DATA.map((h) => {
        const a = h.v3.attrs;
        const skills = SKILL_IDS.filter((s) => (h.v3.skills[s] ?? 0) > 0)
          .sort((x, y) => (h.v3.skills[y] ?? 0) - (h.v3.skills[x] ?? 0) || SKILL_IDS.indexOf(x) - SKILL_IDS.indexOf(y))
          .slice(0, 3)
          .map((s) => `${titleCase(s)} ${h.v3.skills[s]}`)
          .join(", ");
        const party = PARTY_BY_ID[PARTY_DATA.find((p) => p.memberIds.includes(h.id))!.id];
        return [party.memberIds.length === 1 ? `${h.name} (alone)` : `${h.name} (${party.name})`, `${a.strength}/${a.dexterity}/${a.constitution}/${a.mind}/${a.charisma}`, skills, h.v3.combat];
      }),
    ),
    "",
    "## D. One real beat",
    "",
    "(Score ÷ target is the percentage; the **meter** is the 0 to 100 needle position, placed inside the zone of the result.)",
    "",
    workedExample(),
    "",
  );

  return out.join("\n");
}
